FROM python:3.10

RUN apt-get -y update && apt-get install -y --no-install-recommends \
        g++ \
        make \
        cmake \
        wget \
        nginx \
        ca-certificates \
    && rm -rf /var/lib/apt/lists/*

ENV BASE_DIR="/project/opt/"

COPY ./ ./project
WORKDIR /project
RUN pip install poetry==1.5.1
RUN poetry install

CMD ["poetry", "run", "uvicorn", "opt.program.main:app", "--reload", "--host", "0.0.0.0", "--port", "8080"]